import photo1 from "./mask_1.svg";
import photo2 from "./mask_2.svg";

const guests = [
  {
    birthDate: "01.11.1998",
    id: 1,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 2,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 3,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 4,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 5,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 6,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 7,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 8,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 9,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 10,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 11,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 12,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 13,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 14,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 15,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 16,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 17,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 18,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 19,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 20,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 21,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 22,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 23,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 24,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 25,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 26,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 27,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 28,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 29,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 30,
    name: "Светлана",
    surname: "Меньщикова",
  },
  {
    birthDate: "01.01.1998",
    id: 31,
    name: "Татьяна",
    surname: "Царева",
  },
  {
    birthDate: "01.01.1992",
    id: 32,
    name: "Борис",
    surname: "Стрелков",
  },
  {
    birthDate: "01.01.1998",
    id: 33,
    name: "Светлана",
    surname: "Меньщикова",
  },
];

const coaches = [
  {
    birthDate: "01.01.1998",
    id: 1,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 2,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 3,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 4,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 5,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 6,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 7,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 8,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 9,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 10,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 11,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 12,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 13,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 14,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 15,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 16,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 17,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 18,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 19,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 20,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 21,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 22,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 23,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 24,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 25,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 26,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 27,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 28,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 29,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 30,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1998",
    id: 31,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
  {
    birthDate: "01.01.1992",
    id: 32,
    name: "Борис",
    surname: "Стрелков",
    category: "Лыжи. Опыт 5 лет.",
    photo: photo2,
  },
  {
    birthDate: "01.01.1998",
    id: 33,
    name: "Светлана",
    surname: "Меньщикова",
    category: "Сноуборд. Опыт 10 лет.",
    photo: photo1,
  },
];

const skipasses = [
  {
    cost: 3150,
    duration: "Дневной 8:30-16:00",
    id: 1,
  },
  {
    cost: 2150,
    duration: "Полуденный 12:30-16:00",
    id: 2,
  },
  {
    cost: 1150,
    duration: "вечерний 16:00-22:00",
    id: 3,
  },
  {
    cost: 3150,
    duration: "Дневной 8:30-16:00",
    id: 4,
  },
  {
    cost: 2150,
    duration: "Полуденный 12:30-16:00",
    id: 5,
  },
  {
    cost: 1150,
    duration: "вечерний 16:00-22:00",
    id: 6,
  },
];

export { guests, coaches, skipasses };
